// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AGHeader: typeof import('./src/components/AGHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
